name: SurvivalPlus
version: 1.0
main: com.survivalplus.SurvivalPlus
api-version: '1.21'
author: Noah
description: A complete SMP survival plugin

commands:
  help:
    description: SurvivalPlus help menu
    usage: /help
