name: SurvivalPlus
version: 1.0
main: com.survivalplus.SurvivalPlus
api-version: '1.21'
author: Noah
description: Complete SMP survival plugin

softdepend:
  - Geyser-Spigot
  - floodgate

commands:
  help:
    description: Opens SurvivalPlus help menu
    usage: /help
    aliases:
      - survivalplus

permissions:
  survivalplus.admin:
    default: op
